### ISSUE TITLE
Roadmap to 0.2

### ISSUE THREAD

**Issue by mofeing** [UB-Quantic/dqcsim-intel-qs#1]
- [x] Support MPI parallelization
- [x] ~~Support controlled-controlled gates (e.g. Toffoli)~~ #2
- [x] Add option flag for logging macros
- [x] Choose a license
